/**
 * Musenet API
 *
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Band { 
    id?: number;
    name: string;
    genre?: string;
    formedDate?: string;
}

