/**
 * Musenet API
 *
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    createdBy?: string;
    createdDate?: string;
    lastModifiedBy?: string;
    lastModifiedDate?: string;
    id?: number;
    login: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    activated: boolean;
    langKey?: string;
    imageUrl?: string;
    resetDate?: string;
}

