/**
 * Musenet API
 *
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Band } from './band';


export interface UserMusician { 
    id?: number;
    username: string;
    password: string;
    musicalAbility: UserMusician.MusicalAbilityEnum;
    photos?: string;
    photosContentType?: string;
    videos?: string;
    gear?: string;
    friends?: Set<UserMusician>;
    bands?: Set<Band>;
    userMusicians?: Set<UserMusician>;
}
export namespace UserMusician {
    export type MusicalAbilityEnum = 'VOCALIST' | 'GUITARIST' | 'PIANIST' | 'DRUMMER' | 'BASSIST' | 'PRODUCER' | 'DJ';
    export const MusicalAbilityEnum = {
        Vocalist: 'VOCALIST' as MusicalAbilityEnum,
        Guitarist: 'GUITARIST' as MusicalAbilityEnum,
        Pianist: 'PIANIST' as MusicalAbilityEnum,
        Drummer: 'DRUMMER' as MusicalAbilityEnum,
        Bassist: 'BASSIST' as MusicalAbilityEnum,
        Producer: 'PRODUCER' as MusicalAbilityEnum,
        Dj: 'DJ' as MusicalAbilityEnum
    };
}


